name: Run TradingView in Batches

on:
  schedule:
    - cron: "30 7 * * *"
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch_index: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> .env
          echo "SHEET_NAME=${{ secrets.SHEET_NAME }}" >> .env
          echo "SHEET_NAME2=${{ secrets.SHEET_NAME2 }}" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
          echo "GOOGLE_PRIVATE_KEY=\"${{ secrets.GOOGLE_PRIVATE_KEY }}\"" >> .env
          echo "BATCH_INDEX=${{ matrix.batch_index }}" >> .env
          echo "BATCH_SIZE=95" >> .env

      - name: Restore cookies.json from base64
        run: echo "${{ secrets.COOKIES_BASE64 }}" | base64 -d > cookies.json
        shell: bash

      - name: Run Script
        run: node index.js
